force-app/main/default/objects/Log_Entry__c/Log_Entry__c.object-meta.xml
<CustomObject>
    <description>A log record stored when specified events or processes occur, enabling them to be viewed by an admin at a later date.</description>
    <label>Log Entry</label>
    <nameField>
        <label>Log Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Entry__c/fields/Logging_Level__c.field-meta.xml
<CustomField>
    <fullName>Logging_Level__c</fullName>
    <description>The criticality of the logged event. Uses the values of the LoggingLevel Enum.</description>
    <label>Logging Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Entry__c/fields/Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Time_Stamp__c</fullName>
    <description>The date and time an event was raised</description>
    <label>Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LogEntryCleanupBatch_Test.cls
/**
 * @description Unit test covering LogEntryCleanupBatch
 * @group Logger
 */
@isTest
public class LogEntryCleanupBatch_Test {
    /*
     * @description Test to ensure logs are appropriately cleaned up
     */
	@isTest
    public static void executeSuccessful() {    
        Test.startTest();
        // create some test logs
        Logger.info('LogEntryCleanupBatch_Test', 'Test for batch!');
        Logger.warn('LogEntryCleanupBatch_Test', 'Test for batch!');
        Logger.error('LogEntryCleanupBatch_Test', 'Test for batch!');
        Test.stopTest();
        
        // set time stamp back so they will be picked up by the batch
        List<Log_Entry__c> logsList = [SELECT Id FROM Log_Entry__c];
        DateTime old = DateTime.now().addDays(-31);
        for(Log_Entry__c entry: logsList){
            entry.Time_Stamp__c = old;
        }
        update logsList;
        
        // run the batch
        Database.BatchableContext bc;
        LogEntryCleanupBatch batch = new LogEntryCleanupBatch();
        batch.start(bc);
        batch.execute(bc, logsList);
        batch.finish(bc); 
        
        // repull what should be an empty list now
        logsList = [SELECT Id, Logging_Level__c FROM Log_Entry__c];
        System.assertEquals(0, logsList.size(), 'The batch should have deleted all logs, but was ' + logsList.size());
    }    
    
}