force-app/main/default/objects/Log_Entry__c/Log_Entry__c.object-meta.xml
<CustomObject>
    <description>A log record stored when specified events or processes occur, enabling them to be viewed by an admin at a later date.</description>
    <label>Log Entry</label>
    <nameField>
        <label>Log Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Entry__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>The process or code context the event was generated from. Usually the name of the Apex Class, Flow, or Process.</description>
    <label>Context</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Entry__c/fields/Is_Error__c.field-meta.xml
<CustomField>
    <fullName>Is_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the logged event a LoggingLevel.ERROR?</description>
    <label>Is Error?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Entry__c/fields/Logging_Level__c.field-meta.xml
<CustomField>
    <fullName>Logging_Level__c</fullName>
    <description>The criticality of the logged event. Uses the values of the LoggingLevel Enum.</description>
    <label>Logging Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Entry__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Short message describing why an log was published.</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Entry__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The stack trace from a raised exception.</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Logger_Test.cls
@isTest
public class Logger_Test {
    @isTest
    public static void debug_noLogEntry(){
        string testString = 'debug-test123';
        Test.startTest();
            Logger.debug('Logger_Test', testString);
        Test.stopTest();
        List<Log_Entry__c> logs = [SELECT Id FROM Log_Entry__c];
        System.assert(logs.isEmpty(), 'Should not have been any log entry records inserted.');
    }
	@isTest
    public static void info_singleLogEntry(){
        string testString = 'info-test123';
        Test.startTest();
            Logger.info('Logger_Test', testString);
        Test.stopTest();
        Log_Entry__c log = [SELECT Id, Logging_Level__c, Context__c, Message__c FROM Log_Entry__c LIMIT 1];
        System.assertEquals(LoggingLevel.INFO, LoggingLevel.valueOf(log.Logging_Level__c));
        System.assertEquals('Logger_Test', log.Context__c);
        System.assertEquals(testString, log.Message__c);
    }
    @isTest
    public static void warn_singleLogEntry(){
        string testString = 'warn-test123';
        Test.startTest();
            Logger.warn('Logger_Test', testString);
        Test.stopTest();
        Log_Entry__c log = [SELECT Id, Logging_Level__c, Context__c, Message__c FROM Log_Entry__c LIMIT 1];
        System.assertEquals(LoggingLevel.WARN, LoggingLevel.valueOf(log.Logging_Level__c));
        System.assertEquals('Logger_Test', log.Context__c);
        System.assertEquals(testString, log.Message__c);
    }
    @isTest
    public static void error_singleLogEntry(){        
        string testString = 'error-test123';
        Test.startTest();
            Logger.error('Logger_Test', testString);
        Test.stopTest();
        Log_Entry__c log = [SELECT Id, Logging_Level__c, Context__c, Message__c, Is_Error__c FROM Log_Entry__c LIMIT 1];
        System.assertEquals(LoggingLevel.ERROR, LoggingLevel.valueOf(log.Logging_Level__c));
        System.assertEquals('Logger_Test', log.Context__c);
        System.assertEquals(testString, log.Message__c);
        System.assert(log.Is_Error__c);
    }
    @isTest
    public static void exception_singleLogEntry(){        
        string testString = 'exception-test123';
        Test.startTest();
        try{
            throw new LoggerTestException(testString);
        }catch(LoggerTestException e){
            Logger.Exception('Logger_Test', e);
        }
        Test.stopTest();
        Log_Entry__c log = [SELECT Id, Logging_Level__c, Context__c, Message__c, Is_Error__c, Stack_Trace__c FROM Log_Entry__c LIMIT 1];
        System.assertEquals(LoggingLevel.ERROR, LoggingLevel.valueOf(log.Logging_Level__c));
        System.assertEquals('Logger_Test', log.Context__c);
        System.assertEquals(testString, log.Message__c);
        System.assert(log.Is_Error__c);
        System.assert(log.Stack_Trace__c != null);
    }

    public class LoggerTestException extends Exception { }
}