force-app/main/default/objects/Application_Configuration__mdt/Application_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>General key-value-pair configurable settings.</description>
    <label>Application Configuration</label>
    <pluralLabel>Application Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Application_Configuration__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value of the configurable setting</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Entry__c/Log_Entry__c.object-meta.xml
<CustomObject>
    <description>A log record stored when specified events or processes occur, enabling them to be viewed by an admin at a later date.</description>
    <label>Log Entry</label>
    <nameField>
        <label>Log Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LogEntryCleanupBatch.cls
/**
 * @description Batch class to clean up old Log Entry records
 */
global class LogEntryCleanupBatch implements Database.Batchable<sObject> {
    /** Metadata Record containing the number of days into the past to delete logs from */
    global static Application_Configuration__mdt logRetentionConfig = Application_Configuration__mdt.getInstance('Log_Retention_Duration');
    /** Local count of all events deleted in the batches run */ 
    private static integer logCount = 0;
    // Setup the collection of objects to be processed 
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id FROM Log_Entry__c WHERE CreatedDate < LAST_N_DAYS:' + logRetentionConfig != null ? logRetentionConfig.Value__c : '30';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Log_Entry__c> logs) {
        // process collection of records and execute any logic to modify
        try {
            logCount += logs.size();
            Database.delete(logs);
        } catch(Exception e) {
            Logger.exception('LogEntryCleanupBatch', e);
        }
    }
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
        Logger.info('LogEntryCleanupBatch', 'LogEntryCleanupBatch job completed! ' + logCount + ' logs purged.');
    }
    
}